AllCops:
  NewCops: enable

plugins:
  - rubocop-minitest
  - rubocop-rake

# --- Disabled ---

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

# --- Overrides ---

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
